studybud/base/urls.py
from django.urls import path

from .views import home, delete_message, topics_page, activity_page, edit_message, reply_message, add_image

urlpatterns = [
    path('', home, name='home'),

    path('topics/', topics_page, name='topics_page'),
    path('activity', activity_page, name='activity_page'),

    path('delete_message/<int:pk>', delete_message, name='delete_message'),
    path('edit_message/<int:pk>', edit_message, name='edit_message'),
    path('reply_message/<int:pk>', reply_message, name='reply_message'),
    path('room/<int:pk>/add_image/', add_image, name='add_image_room'),
    path('chat/<int:pk>/add_image/', add_image, name='add_image_chat'),
    path('private_room/<int:pk>/add_image/', add_image, name='add_image_private_room'),
]

studybud/private_room/urls.py
from django.urls import path
from .views import private_room, create_private_room, private_rooms_list, update_private_room, priv_room_add_friends, \
    priv_room_delete_friends, delete_private_room


urlpatterns = [
    path('private_room/<int:pk>', private_room, name='private_room'),
    path('create_private_room', create_private_room, name='create_private_room'),
    path('', private_rooms_list, name='private_rooms_list'),
    path('update_private_room/<int:pk>', update_private_room, name='update_private_room'),
    path('delete_private_room/<int:pk>', delete_private_room, name='delete_private_room'),
    path('add_friends_private_room/<int:pk>', priv_room_add_friends, name='add_friend_pr_r'),
    path('private_room/<int:rm_pk>/delete_friend/<int:us_pk>', priv_room_delete_friends, name='delete_priv_room'),
]

studybud/studybud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('room.api.urls')),
    path('friends/', include('friends.urls')),
    path('private_message/', include('private_message.urls')),
    path('room/', include('room.urls')),
    path('private_rooms/', include('private_room.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

studybud/base/models.py
from django.db import models
from accounts.models import User
from private_message.models import Chat
from private_room.models import Private_Room


class Topic(models.Model):
    name = models.CharField(max_length=200)
    updated = models.DateTimeField(auto_now=True, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

    def __str__(self):
        return self.name


class Message(models.Model):
    from room.models import Room
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # One to Many relationship, mes - child, room - father
    room = models.ForeignKey(Room, on_delete=models.CASCADE, null=True)  # Cascade means that if we delete parent(room)-
    # child will dead
    body = models.TextField()  # user should to input smthng here
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    reply = models.IntegerField(blank=True, null=True)
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE, null=True)
    images = models.ImageField(null=True, upload_to='mess_img/')
    private_room = models.ForeignKey(Private_Room, on_delete=models.CASCADE, null=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]  # representation view must not be so large

studybud/private_room/models.py
from django.db import models

from accounts.models import User


class Private_Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=250, null=True, blank=True)
    room_friends = models.ManyToManyField(User, related_name='room_friends', blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name

studybud/room/models.py
from django.db import models

from base.models import Topic
from accounts.models import User


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=250, null=True, blank=True)  # null for DB, blank for Forms
    participants = models.ManyToManyField(User, related_name='participants', blank=True)  # we have User model already,
    # and need to add related name which will be not the same
    updated = models.DateTimeField(auto_now=True)  # auto_now update time after every update
    created = models.DateTimeField(auto_now_add=True)  # auto_now_add make the time only once after creation

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name

studybud/base/forms.py
from django.forms import ModelForm

from .models import Message


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['body']


class MessgImg(ModelForm):
    class Meta:
        model = Message
        fields = ['images']

studybud/private_room/forms.py
from django import forms
from django.db.models import Q
from django.forms import ModelForm

from .models import Private_Room
from accounts.models import User


class PrivateRoomForm(ModelForm):
    class Meta:
        model = Private_Room
        fields = '__all__'
        exclude = ['host']


class PrivateRoomFormCreate(PrivateRoomForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['room_friends'] = forms.MultipleChoiceField(
            choices=[
                (friend.id, f'{friend.username}') for friend in
                User.objects.filter((Q(friends__is_friend=True) &
                                     Q(friends__friend__id=self.instance.host.id))) if
                friend.id != self.instance.host.id and friend not in self.instance.room_friends.all()
            ],
            label='room_friends',
            required=False,
        )

    class Meta(PrivateRoomForm.Meta):
        exclude = ['host', 'name', 'description', 'updated', 'created']

studybud/base/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render

from private_message.models import Chat
from private_room.models import Private_Room
from room.models import Room
from .forms import MessgImg, MessageForm
from .models import Topic, Message


def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    rooms = Room.objects.filter(
        Q(topic__name__icontains=q) |
        Q(name__icontains=q) |
        Q(description__icontains=q) |
        Q(host__first_name__icontains=q)
    ).order_by('-updated')
    topics = Topic.objects.all().order_by('-updated')[0:10]
    room_count = rooms.count()
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))[0:7]
    context = {
        'rooms': rooms,
        'topics': topics,
        'room_count': room_count,
        'room_messages': room_messages
    }
    return render(request, 'base/home.html', context)


def add_image(request, pk):
    room, chat, priv_room = None, None, None
    img = MessgImg()
    if 'private_room' in request.path:
        priv_room = Private_Room.objects.get(id=pk)
        if request.method == 'POST':
            img = MessgImg(request.POST, request.FILES, instance=Message.objects.create(
                user=request.user,
                body='',
                private_room=priv_room
            ))
            if img.is_valid():
                img.save()
                return redirect('private_room', priv_room.id)
    elif 'room' in request.path:
        room = Room.objects.get(id=pk)
        if request.method == 'POST':
            img = MessgImg(request.POST, request.FILES, instance=Message.objects.create(
                user=request.user,
                body='',
                room=room
            ))
            if img.is_valid():
                img.save()
                return redirect('room', room.id)
    else:
        chat = Chat.objects.get(id=pk)
        if request.method == 'POST':
            img = MessgImg(request.POST, request.FILES, instance=Message.objects.create(
                user=request.user,
                body='',
                chat=chat
            ))
            if img.is_valid():
                img.save()
                return redirect('chat', chat.id)
    context = {
        'img': img,
        'room': room,
        'chat': chat,
        'priv_room': priv_room
    }
    return render(request, 'base/add_image.html', context)


@login_required(login_url='login')
def delete_message(request, pk):
    """
    After the end of project I can try to make a func with Celery to delete Topics & Rooms with 0 rooms
    :param request:
    :param pk:
    :return:
    """
    message = Message.objects.get(id=pk)
    if request.user != message.user:
        return HttpResponse('You are not allowe here!!!')
    if request.method == 'POST':
        message.delete()
        if message.room:
            return redirect('room', pk=message.room.id)
        if message.chat:
            return redirect('chat', pk=message.chat.id)
        if message.private_room:
            return redirect('private_room', pk=message.private_room.id)
    context = {'obj': message}
    return render(request, 'base/delete.html', context)


def topics_page(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(name__icontains=q)
    paginator = Paginator(topics, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'topics': topics, 'page_obj': page_obj}
    return render(request, 'base/topics.html', context)


def activity_page(request):
    room_messages = Message.objects.select_related('room').all()
    return render(request, 'base/activity.html', {'room_messages': room_messages})


@login_required(login_url='login')
def edit_message(request, pk):
    messg = Message.objects.get(id=pk)
    form = MessageForm(instance=messg)
    if request.method == 'POST':
        form = MessageForm(request.POST, instance=messg)
        if form.is_valid():
            form.save()
        if messg.room:
            return redirect('room', messg.room.id)
        if messg.chat:
            return redirect('chat', messg.chat.id)
        if messg.private_room:
            return redirect('private_room', messg.private_room.id)
    context = {'form': form, 'messg': messg}
    return render(request, 'base/edit_mess_form.html', context)


@login_required(login_url='login')
def reply_message(request, pk):
    messg = Message.objects.get(id=pk)
    form = MessageForm()
    pow = 'Message.objects.get(id=messg.id)'
    if request.method == 'POST':
        if messg.room:
            messag = Message.objects.create(
                user=request.user,
                room=messg.room,
                body=request.POST.get('body'),
                reply=messg.id
            )
            return redirect('room', messg.room.id)
        elif messg.private_room:
            messag = Message.objects.create(
                user=request.user,
                private_room=messg.private_room,
                body=request.POST.get('body'),
                reply=messg.id
            )
            return redirect('private_room', messg.private_room.id)
        else:
            messag = Message.objects.create(
                user=request.user,
                chat=messg.chat,
                body=request.POST.get('body'),
                reply=messg.id
            )
            return redirect('chat', messg.chat.id)
    context = {'form': form, 'messg': messg, 'pow': pow}
    return render(request, 'base/reply_messg.html', context)

studybud/private_room/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect

from .forms import PrivateRoomFormCreate, PrivateRoomForm
from .models import Private_Room
from base.models import Message, Topic
from accounts.models import User


def priv_room_add_friends(request, pk):
    priv_room = Private_Room.objects.get(id=pk)
    form = PrivateRoomFormCreate(instance=priv_room)
    if request.method == 'POST':
        form = PrivateRoomFormCreate(request.POST, instance=priv_room)
        if form.is_valid():
            rm = form.save(commit=False)
            temp = form.cleaned_data.get("room_friends")
            for i in temp:
                priv_room.room_friends.add(User.objects.get(id=i))
                priv_room.save()
            priv_room.save()
            rm.save()
            return redirect('private_room', priv_room.id)
    context = {'form': form, 'priv_room': priv_room}
    return render(request, 'private_room/priv_room_add_friends.html', context)


def priv_room_delete_friends(request, rm_pk, us_pk):
    friend = User.objects.get(id=us_pk)
    priv_room = Private_Room.objects.get(id=rm_pk)
    if request.method == 'POST':
        priv_room.room_friends.remove(friend)
        return redirect('private_room', priv_room.id)
    context = {'obj': friend}
    return render(request, 'base/delete.html', context)
#

def private_room(request, pk):
    priv_room = Private_Room.objects.get(id=pk)
    msgs = priv_room.message_set.all()
    friends = priv_room.room_friends.all()
    ids = []
    for i in msgs:
        if i.reply:
            ids.append(i.reply)
    mesag = Message.objects.filter(id__in=ids)
    if request.method == "POST":
        msg = Message.objects.create(
            user=request.user,
            private_room=priv_room,
            body=request.POST.get('body')
        )
        priv_room.updated = msg.created
        priv_room.save()
        return redirect('private_room', pk=priv_room.id)
    context = {
        'priv_room': priv_room,
        'msgs': msgs,
        'friends': friends,
        'mesag': mesag
    }
    return render(request, 'private_room/private_room.html', context)


@login_required(login_url='login')
def create_private_room(request):
    form = PrivateRoomForm()
    if request.method == 'POST':
        form = PrivateRoomForm(request.POST)
        if form.is_valid():
            priv_room = form.save(commit=False)
            priv_room.host = request.user
            priv_room.save()
            priv_room.room_friends.add(request.user.id)
            return redirect('add_friend_pr_r', priv_room.id)
    context = {'form': form}
    return render(request, 'private_room/private_room_form.html', context)


def update_private_room(request, pk):
    private_room = Private_Room.objects.get(id=pk)
    form = PrivateRoomForm(instance=private_room)
    if request.method == 'POST':
        form = PrivateRoomForm(request.POST)
        private_room.name = request.POST.get('name')
        private_room.save()
        return redirect('private_room', pk=private_room.id)
    context = {'form': form, 'private_room': private_room}
    return render(request, 'private_room/private_room_form.html', context)


@login_required(login_url='login')
def delete_private_room(request, pk):
    priv_room = Private_Room.objects.get(id=pk)
    if request.method == 'POST':
        priv_room.delete()
        return redirect('home')
    context = {'obj': priv_room}
    return render(request, 'base/delete.html', context)


def private_rooms_list(request):
    private_rooms = Private_Room.objects.filter(room_friends=request.user)
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    users = User.objects.filter(room_friends__room_friends=request.user)
    topics = Topic.objects.all().order_by('-updated')[0:10]
    room_messages = Message.objects.filter(Q(room__topic__name__icontains=q))
    rooms_count = private_rooms.count()
    context = {
        'private_rooms': private_rooms,
        'topics': topics,
        'room_messages': room_messages,
        'rooms_count': rooms_count,
        'users': users
    }
    return render(request, 'private_room/private_rooms_list.html', context)

studybud/base/templates/base/activity.html
{% extends 'base_temp.html' %}

 {% block content %}


    <main class="layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Recent Activities</h3>
            </div>
          </div>

          <div class="activities-page layout__body">
               {% for message in room_messages %}
          {% if message.room %}
          <div class="activities__box">
            <div class="activities__boxHeader roomListRoom__header">
              <a href="{% url 'user_profile' message.user.pk %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                  <img src="{{ message.user.avatar.url}}" />
                </div>
                <p>
                  @{{ message.user.username }}
                  <span>{{ message.created|timesince }} ago</span>
                </p>
              </a>

                {% if request.user == message.user %}
              <div class="roomListRoom__actions">
                <a href="{% url 'delete_message' message.id %}">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>remove</title>
                    <path
                      d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                    ></path>
                  </svg>
                </a>
              </div>
                {% endif %}
            </div>

            <div class="activities__boxContent">

              <p>replied to room “<a href="{% url 'room' message.room.id %}">{{ message.room}}</a>”</p>
              <div class="activities__boxRoomContent">
                  {{ message.body}}
              </div>
            </div>

          </div>
                   {% endif %}
    {% endfor %}
          </div>
        </div>
      </div>
    </main>

{% endblock %}

studybud/base/templates/base/activity_component.html
<div class="activities">
          <div class="activities__header">
            <h2>Recent Activities</h2>
          </div>

        {% for message in room_messages %}
            {% if message.room is not null %}
          <div class="activities__box">
            <div class="activities__boxHeader roomListRoom__header">
              <a href="{% url 'user_profile' message.user.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                  <img src="{{ message.user.avatar.url }}" />
                </div>
                <p>
                  @{{ message.user.username}}
                  <span>{{ message.created|timesince }} ago</span>
                </p>
              </a>

                {% if request.user == message.user %}
              <div class="roomListRoom__actions">
                <a href="{% url 'delete_message' message.user.id %}">
                  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>remove</title>
                    <path
                      d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                    ></path>
                  </svg>
                </a>
              </div>
                {% endif %}
            </div>
            <div class="activities__boxContent">
              <p>replied to room “<a href="{% url 'room' message.room.id %}">{{ message.room}}</a>”</p>
              <div class="activities__boxRoomContent">
                  {{ message.body}}
              </div>
            </div>

          </div>
            {% endif %}
    {% endfor %}


        </div>

studybud/base/templates/base/add_image.html
{% extends 'base_temp.html' %}


{% block content %}

    <main class="update-account layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{ request.META.HTTP_REFERER }}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Add image</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
{#                    {% for field in img %}#}
                        <div class="form__group">
{#                            <label for="profile_pic">{{ img.images.label }}</label>#}
                            {{img.as_p}}
{#                            {{ msg.images.url }}#}
                            {% if img.errors %}
{#                        {% for field in form %}#}
                            {% for error in img.images.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
{#                            {% endfor %}#}
                        {% endfor %}
{#                        {% for error in form.non_field_errors %}#}
{#                            <div class="alert alert-danger">#}
{#                                <strong>{{ error|escape }}</strong>#}
{#                            </div>#}
{#                        {% endfor %}#}
                    {% endif %}

                        </div>

                        <div class="form__action">
                            <button href="{% url 'home' %}" class="btn btn--main" type="submit">Update</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
      </div>
    </main>

{% endblock %}

studybud/base/templates/base/delete.html
{% extends 'base_temp.html' %}

{% block content %}

    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{ request.META.HTTP_REFERER }}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form class="form" action="" method="POST">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{ obj }}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm" />
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

studybud/base/templates/base/edit_mess_form.html
{% extends 'base_temp.html' %}

{% block content %}

<main class="create-room layout">
    <div class="container">
      <div class="layout__box">
        <div class="layout__boxHeader">
          <div class="layout__boxTitle">
            <a href=" {{ request.META.HTTP_REFERER }} ">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>arrow-left</title>
                <path
                  d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                </path>
              </svg>
            </a>
            <h3>Edit message</h3>
          </div>
        </div>
        <div class="layout__body">

          <form class="form" action="" method="POST">
              {% csrf_token %}

              <div class="form__group">
              <label for="room_description">Message:</label>

                  {{ form.body }}
            </div>


            <div class="form__action">
              <button  class="btn btn--main" type="submit" >Submit</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </main>


{% endblock %}

studybud/base/templates/base/topics.html
{% extends 'base_temp.html' %}

 {% block content %}


    <main class="create-room layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <a href="{% url 'home' %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>arrow-left</title>
                  <path
                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                  ></path>
                </svg>
              </a>
              <h3>Browse Topics</h3>
            </div>
          </div>

          <div class="topics-page layout__body">
            <form action="" method="GET" class="header__search">
              <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>search</title>
                  <path
                    d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                  ></path>
                </svg>
                <input name="q" placeholder="Search for topics" />
              </label>
            </form>

            <ul class="topics__list">
              <li>
                <a href="{% url 'topics_page' %}" class="active">All <span>{{ topics.count }}</span></a>
              </li>
                {% for topic in page_obj %}
              <li>
                <a href="{% url 'home' %}?q={{ topic.name }}">{{ topic.name }} <span>{{ topic.room_set.all.count }}</span></a>
              </li>
                {% endfor %}

                <div class="pagination">
                    <span class="step-links">
                        {% if page_obj.has_previous %}
                            <a href="?page=1">&laquo; first</a>
                            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                            </span>
                        {% endif %}

                        <span class="current">
                            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                        </span>


                        {% if page_obj.has_next %}
                            <a href="?page={{ page_obj.next_page_number }}">next</a>
                            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                        {% endif %}
                </div>
                        </ul>
                  </div>
                </div>
              </div>
            </main>

        {% endblock %}

studybud/base/templates/base/topics_component.html
<div class="topics">
          <div class="topics__header">
            <h2>Browse Topics</h2>
          </div>
          <ul class="topics__list">
            <li>
                <a href="{% url 'home' %}" class="active">All </a> {# <span>{{ topics.count }}</span></a>#}
            </li>
              {% for topic in topics %}
            <li>
              <a href="{% url 'home'%}?q={{ topic.name }}">{{ topic.name }}
                  <span>{{ topic.room_set.all.count }}</span></a>
            </li>
                  {% endfor %}

          </ul>
          <a class="btn btn--link" href="{% url 'topics_page' %}">
            More
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>chevron-down</title>
              <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
            </svg>
          </a>
        </div>